### ISSUE TITLE
double sqrt in PerceiverAttention

### ISSUE THREAD

**Issue by 4IK1d** [muzishen/IMAGDressing#48]
Hi thanks for you wonderful work in VTON,

however, It seem we have `sqrt` twice in `PerceiverAttention`, should this be a bug?

https://github.com/muzishen/IMAGDressing/blob/ef0d64358d2f3b9260044d8d39f9ae493f9fe0be/adapter/resampler.py#L71C9-L71C56

**Comment by muzishen** [comment]
Thank you. You're correct that there are two sqrt operations in the scaling factor in PerceiverAttention. This is not a bug but an intentional design choice aimed at improving numerical stability, especially in scenarios with float16 precision.

By using 1 / sqrt(sqrt(dim_head)), the scaling reduces the magnitude of the dot products, which helps maintain stability during the softmax computation. However, if this design choice does not align with your requirements, you can safely modify it to the standard 1 / sqrt(dim_head) without affecting the core functionality.

**Comment by 4IK1d** [comment]
> Thank you. You're correct that there are two sqrt operations in the scaling factor in PerceiverAttention. This is not a bug but an intentional design choice aimed at improving numerical stability, especially in scenarios with float16 precision.
> 
> By using 1 / sqrt(sqrt(dim_head)), the scaling reduces the magnitude of the dot products, which helps maintain stability during the softmax computation. However, if this design choice does not align with your requirements, you can safely modify it to the standard 1 / sqrt(dim_head) without affecting the core functionality.

Thanks for your kind and detailed explaination.
