### ISSUE TITLE
How to perform the eval_s.py

### ISSUE THREAD

**Issue by linlinx666** [muzishen/IMAGDressing#50]
('--cloth_path', type=str, help='input cloth path')
('--cloth_mask_path', type=str, help='generate cloth mask path')
('--model_path', type=str, help='generate model path')
('--pose_path', type=str, help='input pose path')
('--face_path', type=str, help='input face path')
('--text_prompts', type=list, help='input text prompts list')
The file IGPair contains  body_mask, clothes, densepose, IGPair_Test, images, and openpose.
What is the relationship between the files？

**Comment by WhiteJiang** [comment]
Thank you for your interest in our project. Because our project is only generated based on reference clothes, the generated models are diverse. For this reason, we do not provide openpose and cloth_mask_path, etc. for testing. If you want to compare, you can use our test files for evaluation after getting the openpose and other results yourself.
